export const listBankModel = [
    { id: 1, name_bank: 'NHA NUOC-101' },
    { id: 2, name_bank: 'CONG THUONG VN (VIETINBANK)-201' },
    { id: 3, name_bank: 'DAU TU VA PHAT TRIEN VN (BIDV)-202' },
    { id: 4, name_bank: 'NGOAI THUONG VN (VCB)-203' },
    { id: 5, name_bank: 'NONG NGHIEP VA PTNT VN (AGRIBANK)-204' },
    { id: 6, name_bank: 'CHINH SACH XA HOI (VBSP)-207' },
    { id: 7, name_bank: 'PHAT TRIEN VIET NAM (VDB)-208' },
    { id: 8, name_bank: 'HANG HAI (MARITIMEBANK-MSB)-302' },
    { id: 9, name_bank: 'SAI GON THUONG TIN (SACOMBANK)-303' },
    { id: 10, name_bank: 'DONG A (DAB)-304' },
    { id: 11, name_bank: 'XUAT NHAP KHAU (EXIMBANK)-305' },
    { id: 12, name_bank: 'NAM A-306' },
    { id: 13, name_bank: 'A CHAU (ACB)-307' },
    { id: 14, name_bank: 'SAI GON CONG THUONG-308' },
    { id: 15, name_bank: 'VIET NAM THINH VUONG (VPBANK)-309' },
    { id: 16, name_bank: 'QUAN DOI (MB)-311' },
    { id: 17, name_bank: 'BAC A (NASB)-313' },
    { id: 18, name_bank: 'QUOC TE (VIB)-314' },
    { id: 19, name_bank: 'DONG NAM A (SEA BANK)-317' },
    { id: 20, name_bank: 'DAI DUONG (OCEAN BANK)-319' },
    { id: 21, name_bank: 'DAU KHI TOAN CAU (GPBANK)-320' },
    { id: 22, name_bank: 'PHAT TRIEN TP HCM (HDBANK)-321' },
    { id: 23, name_bank: 'AN BINH (AB BANK)-323' },
    { id: 24, name_bank: 'VIET HOA-324' },
    { id: 25, name_bank: 'BAN VIET (VIETCAPITALBANK)-327' },
    { id: 26, name_bank: 'PHUONG DONG (OCB)-333' },
    { id: 27, name_bank: 'SAI GON (SCB)-334' },
    { id: 28, name_bank: 'XAY DUNG VIET NAM (VNCB)-339' },
    { id: 29, name_bank: 'XANG DAU PETROLIMEX (PGBANK)-341' },
    { id: 30, name_bank: 'SAI GON - HA NOI (SHB)-348' },
    { id: 31, name_bank: 'QUOC DAN (NCB)-352' },
    { id: 32, name_bank: 'KIEN LONG (KIENLONGBANK)-353' },
    { id: 33, name_bank: 'VIET A (VIETABANK)-355' },
    { id: 34, name_bank: 'VIET NAM THUONG TIN (VIETBANK)-356' },
    { id: 35, name_bank: 'BUU DIEN LIEN VIET (LPB)-357' },
    { id: 36, name_bank: 'TIEN PHONG (TIENPHONGBANK)-358' },
    { id: 37, name_bank: 'BAO VIET (BAOVIETBANK)-359' },
    { id: 38, name_bank: 'DAI CHUNG VN (PVCOMBANK)-360' },
    { id: 39, name_bank: 'BANKNET-401' },
    { id: 40, name_bank: 'PUBLIC VIET NAM-501' },
    { id: 41, name_bank: 'INDOVINA-502' },
    { id: 42, name_bank: 'LD VIET NGA (VRB)-505' },
    { id: 43, name_bank: 'THE SIAM COMMERCIAL BANK PUBLIC-600' },
    { id: 44, name_bank: 'KY THUONG VN (TECHCOMBANK)' },
    { id: 45, name_bank: 'CITIBANK HO CHI MINH-654' },
    { id: 46, name_bank: 'CITIBANK HA NOI-605' },
    { id: 47, name_bank: 'CITIBANK, N.A, SINGAPORE BRANCH' },
    { id: 48, name_bank: 'UNITED OVERSEAS BANK VIET NAM-665' },
    { id: 49, name_bank: 'SHINHAN VIET NAM-616' },
    { id: 50, name_bank: 'STANDARD CHARTERED-604' },
    { id: 51, name_bank: 'BNP PARIBAS CN HCM-614' },
    { id: 52, name_bank: 'BNP PARIBAS CN HA NOI-657' },
    { id: 53, name_bank: 'ANZ VN-602' },
    { id: 54, name_bank: 'MIZUHO CN HA NOI-613' },
    { id: 55, name_bank: 'WOORI VIET NAM-663' },
    { id: 56, name_bank: 'HSBC-617' }
];
