SET @createdBy = 'anonymousUser'
SET @lastModifiedBy = 'anonymousUser'
SET @status = 'ENABLE'
SET @deleted = 0


--     Init data accom category
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Phòng','Phòng nhỏ căn hộ','https://img.icons8.com/ios/25/room.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Nhà riêng','Nhà riêng cá nhân','https://img.icons8.com/pastel-glyph/25/home.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Nhà chung cư','Nhà chung cư mini','https://img.icons8.com/ios/25/apartment.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Nhà thuyền','Nhà thuyền du khách','https://img.icons8.com/external-outline-black-m-oki-orlando/25/external-boat-house-types-of-houses-outline-outline-black-m-oki-orlando.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Khu cắm trại','Khu cắm trại xịn xò','https://img.icons8.com/ios-filled/25/campsite.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Biệt thự','Biệt thự tỷ đô','https://img.icons8.com/external-others-abderraouf-omara/25/external-villa-real-estate-and-houses-others-abderraouf-omara.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Homestay','Home stay','https://img.icons8.com/quill/25/home.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Nhà trên núi','Nhà trên núi siêu mát','https://img.icons8.com/ios-filled/25/mountain.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Garden','Nhà vườn nông thôn','https://img.icons8.com/ios/25/garden-sprinkler.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Bãi biển','Chỗ ở gần bãi biển','https://img.icons8.com/ios/25/beach.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Cabin','Căn hộ cabin','https://img.icons8.com/external-victoruler-outline-victoruler/25/external-cabin-christmas-victoruler-outline-victoruler.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Thuyền','Nhà thuyền cho thuê','https://img.icons8.com/ios/25/sail-boat.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Nhà trên cây','Nhà trang trí trên cây','https://img.icons8.com/external-outline-black-m-oki-orlando/25/external-tree-house-types-of-houses-outline-outline-black-m-oki-orlando.png',@status)
INSERT INTO accommodation_categories(created_by,created_date,last_modified_by,last_modified_date,deleted,accom_cate_name,description,icon,status) VALUES (@createdBy,CURRENT_TIMESTAMP,@lastModifiedBy,CURRENT_TIMESTAMP,@deleted,'Nông trại','Nông trại gia đình','https://img.icons8.com/dotty/25/farm-2.png',@status)